name: Run Lottery Script

on:
  schedule:
    - cron: "0 16 * * *"   # UTC 16:00 = 北京/东京 0:00
  workflow_dispatch:

jobs:
  run-lottery:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run script
        env:
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}   # ✅ 从 Secrets 注入
        run: python sync.py

      - name: Upload JSON artifact (keep 3 days)
        uses: actions/upload-artifact@v4
        with:
          name: lottery-json
          path: "*.json"
          retention-days: 3
